apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: guestbook-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
spec:
  selector:
    app: guestbook
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
